name: Humble

on:
  push:
    branches: [main, chore/*, feat/*, fix/*]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base
    env:
      PIP_BREAK_SYSTEM_PACKAGES: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup workspace
        run: |
          mkdir -p /tmp/ws/src
          ln -s $GITHUB_WORKSPACE /tmp/ws/src/messages

      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install -y python3-colcon-common-extensions git
          cd /tmp/ws
          . /opt/ros/humble/setup.sh
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y --rosdistro humble

      - name: Build
        run: |
          cd /tmp/ws
          . /opt/ros/humble/setup.sh
          colcon build --packages-select muto_msgs

      - name: Test
        run: |
          cd /tmp/ws
          . /opt/ros/humble/setup.sh
          . install/setup.sh
          colcon test --packages-select muto_msgs --event-handlers console_direct+
          colcon test-result --verbose
